- packages/base-monaco-editor/package.json
see https://github.com/alibaba/lowcode-engine/issues/81
> fix: 修正 @alilc/lowcode-plugin-base-monaco-editor 的依赖

- packages/plugin-components-pane/demo/component.md
- packages/plugin-components-pane/demo/epoch.md
- packages/plugin-components-pane/demo/usage.md
- packages/plugin-components-pane/src/index.tsx
> fix: Panel for Search

- demo/public/index.html
- package.json
- packages/plugin-datasource-pane/src/classname-setter/index.tsx
- packages/plugin-datasource-pane/src/components/ClassNameView/ClassNameView.tsx
- packages/plugin-datasource-pane/src/pane/index.tsx
修复 https://github.com/alibaba/lowcode-engine/issues/466
> Hotfix data source

- packages/plugin-datasource-pane/src/components/DataSourceListItem/DataSourceListItem.tsx
> fix: missing key

- demo/src/index.ts
- packages/plugin-datasource-pane/src/components/DataSourceImport/DataSourceImport.tsx
- packages/plugin-datasource-pane/src/pane/DataSourcePane.tsx
> fix: support data source import

- packages/plugin-datasource-pane/src/pane/index.scss
Browser client can't see part of last item
> fix: fixed bug where the panel content overflowed

- packages/plugin-datasource-pane/src/components/DataSourceForm/DataSourceForm.tsx
- packages/plugin-datasource-pane/src/components/Forms/form-lazy-obj.tsx
Close https://github.com/alibaba/lowcode-engine/issues/243
Close https://github.com/alibaba/lowcode-engine/issues/191
Close https://github.com/alibaba/lowcode-engine/issues/783
> Hotfix datasource

- demo/src/index.ts
- packages/plugin-datasource-pane/src/components/DataSourceExport/DataSourceExport.tsx
- packages/plugin-datasource-pane/src/components/DataSourceImport/DataSourceImport.tsx
- packages/plugin-datasource-pane/src/components/DataSourceListItem/DataSourceListItem.tsx
- packages/plugin-datasource-pane/src/utils/stateMachine.ts
1. 格式化导入导出面板样式
2. 开放导出功能
3. 排序按钮跟文字重叠问题
> Hotfix export

- packages/plugin-schema/README.md
- packages/plugin-schema/build.json
- packages/plugin-schema/package.json
- packages/plugin-schema/src/editor.tsx
- packages/plugin-schema/src/index.tsx
增加项目级schema展示能里，通过 isProjectSchema 控制
> feat(plugin-schema): add isProjectSchema option

- packages/plugin-components-pane/src/index.module.scss
- packages/plugin-components-pane/src/index.tsx
Signed-off-by: <xdx1770796956@gmail.com>
> fix: scroll pane content when search component

- packages/plugin-components-pane/src/index.tsx
> fix: #1060

- packages/plugin-simulator-size/package.json
- packages/plugin-simulator-size/src/index.tsx
close https://github.com/alibaba/lowcode-engine/issues/1542
> fix: fix lowcode-plugin-simulator-select plug-in default selection and configuration inconsistency

- packages/plugin-schema/src/editor.tsx
fix https://github.com/alibaba/lowcode-engine/issues/1605
> fix: fix schema-plugin not update when the panel is displayed

- packages/plugin-components-pane/src/components/Component/index.tsx
- packages/plugin-components-pane/src/index.tsx
- packages/plugin-components-pane/src/utils/transform.ts
在plugin-components-pane中完善多语言切换功能，我在https://github.com/alibaba/lowcode-engine/issues/1412 这个里面提的，这个插件实现多语言的方法有所不同，我按照插件原先的方案完善
> feat: complete i18n in plugin-components-pane

- packages/plugin-code-editor/src/components/JSEditor/JsEditor.tsx
解决这个 issue ：https://github.com/alibaba/lowcode-engine/issues/1600
原来的做法是将新函数插入到最后一行前面。
现在改成找到最后一个 } 符号，插入到它之前
> fix(plugin-code-editor): add function out of class

- packages/plugin-schema/src/editor.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1715
> fix: fix the problem that the schema panel at the project level is displayed incorrectly

- packages/plugin-code-editor/src/pane/index.tsx
> fix(plugin-code-editor): change to use skeleton.onShowPanel and skeleton.onHidePanel

- packages/base-monaco-editor/src/helper.ts
close https://github.com/alibaba/lowcode-engine/issues/1851
> feat: add overrideServices props

- packages/plugin-components-pane/src/pane/index.tsx
> fix: fix english keyword search error

- packages/action-block/src/index.tsx
- html2canvas: https://html2canvas.hertzen.com/
- node: type Node = designerCabin.Node<IPublicTypeNodeSchema>
> refactor(action-block): remove log for html2canvas and node

- packages/plugin-undo-redo/package.json
- packages/plugin-undo-redo/src/index.tsx
fix: https://github.com/alibaba/lowcode-engine/issues/1610
> fix: remove event listener for document and history

- packages/plugin-components-pane/src/components/Component/index.module.scss
Reverts alibaba/lowcode-plugins#79
部分用户，构建会出现问题，先回滚
> Revert "Update index.module.scss"

- packages/plugin-multiple-editor/README.md
> docs(plugin-multiple-editor): update readme.md

- packages/plugin-multiple-editor/src/Service.ts
- packages/plugin-multiple-editor/src/index.tsx
editor.on event is out of date, change to use skeleton.onShowPanel and skeleton.onHidePanel , it works
> fix(plugin-multiple-editor): use skeleton.onShowPanel and skeleton.onHidePanel

- packages/plugin-code-editor/src/components/ErrorBoundary/ErrorBoundary.less
- packages/plugin-code-editor/src/components/ErrorBoundary/ErrorBoundary.tsx
> fix: remove plugin-code-editor ErrorBoundary css-module

- packages/plugin-view-manager-pane/src/components/addFile/index.tsx
- packages/plugin-view-manager-pane/src/index.tsx
Support custom add file component, not just add new page and new component.
> feat: add renderAddFileComponent option

- packages/plugin-multiple-editor/package.json
Reverts alibaba/lowcode-plugins#106
> Revert "feat: 修改版本号"
